using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;

namespace TwitterBootstrapMVC
{
    public enum Icons
    {
        _not_set,
        [Description("icon-glass")]
        glass,
        [Description("icon-music")]
        music,
        [Description("icon-search")]
        search,
        [Description("icon-envelope")]
        envelope,
        [Description("icon-heart")]
        heart,
        [Description("icon-star")]
        star,
        [Description("icon-star-empty")]
        star_empty,
        [Description("icon-user")]
        user,
        [Description("icon-film")]
        film,
        [Description("icon-th-large")]
        th_large,
        [Description("icon-th")]
        th,
        [Description("icon-th-list")]
        th_list,
        [Description("icon-ok")]
        ok,
        [Description("icon-remove")]
        remove,
        [Description("icon-zoom-in")]
        zoom_in,
        [Description("icon-zoom-out")]
        zoom_out,
        [Description("icon-off")]
        off,
        [Description("icon-signal")]
        signal,
        [Description("icon-cog")]
        cog,
        [Description("icon-trash")]
        trash,
        [Description("icon-home")]
        home,
        [Description("icon-file")]
        file,
        [Description("icon-time")]
        time,
        [Description("icon-road")]
        road,
        [Description("icon-download-alt")]
        download_alt,
        [Description("icon-download")]
        download,
        [Description("icon-upload")]
        upload,
        [Description("icon-inbox")]
        inbox,
        [Description("icon-play-circle")]
        play_circle,
        [Description("icon-repeat")]
        repeat,
        [Description("icon-refresh")]
        refresh,
        [Description("icon-list-alt")]
        list_alt,
        [Description("icon-lock")]
        g_lock,
        [Description("icon-flag")]
        flag,
        [Description("icon-headphones")]
        headphones,
        [Description("icon-volume-off")]
        volume_off,
        [Description("icon-volume-down")]
        volume_down,
        [Description("icon-volume-up")]
        volume_up,
        [Description("icon-qrcode")]
        qrcode,
        [Description("icon-barcode")]
        barcode,
        [Description("icon-tag")]
        tag,
        [Description("icon-tags")]
        tags,
        [Description("icon-book")]
        book,
        [Description("icon-bookmark")]
        bookmark,
        [Description("icon-print")]
        print,
        [Description("icon-camera")]
        camera,
        [Description("icon-font")]
        font,
        [Description("icon-bold")]
        bold,
        [Description("icon-italic")]
        italic,
        [Description("icon-text-height")]
        text_height,
        [Description("icon-text-width")]
        text_width,
        [Description("icon-align-left")]
        align_left,
        [Description("icon-align-center")]
        align_center,
        [Description("icon-align-right")]
        align_right,
        [Description("icon-align-justify")]
        align_justify,
        [Description("icon-list")]
        list,
        [Description("icon-indent-left")]
        indent_left,
        [Description("icon-indent-right")]
        indent_right,
        [Description("icon-facetime-video")]
        facetime_video,
        [Description("icon-picture")]
        picture,
        [Description("icon-pencil")]
        pencil,
        [Description("icon-map-marker")]
        map_marker,
        [Description("icon-adjust")]
        adjust,
        [Description("icon-tint")]
        tint,
        [Description("icon-edit")]
        edit,
        [Description("icon-share")]
        share,
        [Description("icon-check")]
        check,
        [Description("icon-move")]
        move,
        [Description("icon-step-backward")]
        step_backward,
        [Description("icon-fast-backward")]
        fast_backward,
        [Description("icon-backward")]
        backward,
        [Description("icon-play")]
        play,
        [Description("icon-pause")]
        pause,
        [Description("icon-stop")]
        stop,
        [Description("icon-forward")]
        forward,
        [Description("icon-fast-forward")]
        fast_forward,
        [Description("icon-step-forward")]
        step_forward,
        [Description("icon-eject")]
        eject,
        [Description("icon-chevron-left")]
        chevron_left,
        [Description("icon-chevron-right")]
        chevron_right,
        [Description("icon-plus-sign")]
        plus_sign,
        [Description("icon-minus-sign")]
        minus_sign,
        [Description("icon-remove-sign")]
        remove_sign,
        [Description("icon-ok-sign")]
        ok_sign,
        [Description("icon-question-sign")]
        question_sign,
        [Description("icon-info-sign")]
        info_sign,
        [Description("icon-screenshot")]
        screenshot,
        [Description("icon-remove-circle")]
        remove_circle,
        [Description("icon-ok-circle")]
        ok_circle,
        [Description("icon-ban-circle")]
        ban_circle,
        [Description("icon-arrow-left")]
        arrow_left,
        [Description("icon-arrow-right")]
        arrow_right,
        [Description("icon-arrow-up")]
        arrow_up,
        [Description("icon-arrow-down")]
        arrow_down,
        [Description("icon-share-alt")]
        share_alt,
        [Description("icon-resize-full")]
        resize_full,
        [Description("icon-resize-small")]
        resize_small,
        [Description("icon-plus")]
        plus,
        [Description("icon-minus")]
        minus,
        [Description("icon-asterisk")]
        asterisk,
        [Description("icon-exclamation-sign")]
        exclamation_sign,
        [Description("icon-gift")]
        gift,
        [Description("icon-leaf")]
        leaf,
        [Description("icon-fire")]
        fire,
        [Description("icon-eye-open")]
        eye_open,
        [Description("icon-eye-close")]
        eye_close,
        [Description("icon-warning-sign")]
        warning_sign,
        [Description("icon-plane")]
        plane,
        [Description("icon-calendar")]
        calendar,
        [Description("icon-random")]
        random,
        [Description("icon-comment")]
        comment,
        [Description("icon-magnet")]
        magnet,
        [Description("icon-chevron-up")]
        chevron_up,
        [Description("icon-chevron-down")]
        chevron_down,
        [Description("icon-retweet")]
        retweet,
        [Description("icon-shopping-cart")]
        shopping_cart,
        [Description("icon-folder-close")]
        folder_close,
        [Description("icon-folder-open")]
        folder_open,
        [Description("icon-resize-vertical")]
        resize_vertical,
        [Description("icon-resize-horizontal")]
        resize_horizontal,
        [Description("icon-hdd")]
        hdd,
        [Description("icon-bullhorn")]
        bullhorn,
        [Description("icon-bell")]
        bell,
        [Description("icon-certificate")]
        certificate,
        [Description("icon-thumbs-up")]
        thumbs_up,
        [Description("icon-thumbs-down")]
        thumbs_down,
        [Description("icon-hand-right")]
        hand_right,
        [Description("icon-hand-left")]
        hand_left,
        [Description("icon-hand-up")]
        hand_up,
        [Description("icon-hand-down")]
        hand_down,
        [Description("icon-circle-arrow-right")]
        circle_arrow_right,
        [Description("icon-circle-arrow-left")]
        circle_arrow_left,
        [Description("icon-circle-arrow-up")]
        circle_arrow_up,
        [Description("icon-circle-arrow-down")]
        circle_arrow_down,
        [Description("icon-globe")]
        globe,
        [Description("icon-wrench")]
        wrench,
        [Description("icon-tasks")]
        tasks,
        [Description("icon-filter")]
        filter,
        [Description("icon-briefcase")]
        briefcase,
        [Description("icon-fullscreen")]
        fullscreen
    }
}
